---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - deployment-fdk-dataset-event-publisher.yaml
  - deployment-fdk-data-service-event-publisher.yaml
  - deployment-fdk-concept-event-publisher.yaml
  - deployment-fdk-event-event-publisher.yaml
  - deployment-fdk-information-model-event-publisher.yaml
  - deployment-fdk-service-event-publisher.yaml
  - ../base
