[package]
name = "fdk-kafka-event-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
async-trait = "0.1.89"
chrono = "0.4.42"
lapin = "3.7.2"
lazy_static = "1.5.0"
prometheus = "0.14.0"
rdkafka = "0.38.0"
reqwest = "0.12.24"
schema_registry_converter = { version = "4.6.1", features = ["avro"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tokio-executor-trait = "3.1.0"
tokio-reactor-trait = "4.1.1"
tracing = "0.1.41"
tracing-subscriber =  { version = "0.3.20", features = ["json"] }
