---
services:
  # Kafka in KRaft mode (no Zookeeper needed)
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
    volumes:
      - ./kafka:/kafka
    # Creates custom topics and starts kafka process (in parallel).
    command:
      - sh
      - -c
      - (sh /kafka/create_topics.sh) & /etc/confluent/docker/run
    # Ready when custom topics are created.
    # Make sure number at the end (after 'grep') matches desired topics.
    healthcheck:
      test: /bin/kafka-topics --bootstrap-server 127.0.0.1:9092 --list
      interval: 3s

  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 3s
      retries: 10

  # Registers schemas once schema-registry is up.
  schema-registrer:
    image: dwdraju/alpine-curl-jq
    volumes:
      - ./kafka:/kafka
    command: sh /kafka/create_schemas.sh
    environment:
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
    depends_on:
      schema-registry:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
