---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-event-event-publisher
  labels:
    fdk.service: fdk-event-event-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-event-event-publisher
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: fdk-event-event-publisher
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: fdk-event-event-publisher
          image: fdk-event-event-publisher
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 100Mi
          livenessProbe:
            exec:
              command:
                - "true"
          readinessProbe:
            exec:
              command:
                - "true"
      restartPolicy: Always
