---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-fdk-dataset-event-publisher.yaml
  - service-fdk-concept-event-publisher.yaml
images:
  - name: fdk-dataset-event-publisher
    newName: eu.gcr.io/digdir-fdk-infra/fdk-dataset-event-publisher
    newTag: $(GIT_COMMIT_SHA)
