---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-fdk-dataset-event-publisher.yaml
  - service-fdk-data-service-event-publisher.yaml
  - service-fdk-concept-event-publisher.yaml
  - service-fdk-event-event-publisher.yaml
  - service-fdk-information-model-event-publisher.yaml
  - service-fdk-service-event-publisher.yaml
