---
apiVersion: v1
kind: Service
metadata:
  name: fdk-dataset-event-publisher
spec:
  selector:
    fdk.service: fdk-dataset-event-publisher
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8081
  type: NodePort
