---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - deployment-fdk-dataset-event-publisher.yaml
  - deployment-fdk-data-service-event-publisher.yaml
  - deployment-fdk-concept-event-publisher.yaml
  - ../base
