---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - deployment-fdk-dataset-event-publisher.yaml
  - deployment-fdk-data-service-event-publisher.yaml
  - deployment-fdk-concept-event-publisher.yaml
  - deployment-fdk-information-model-event-publisher.yaml
  - ../base
images:
  - name: fdk-dataset-event-publisher
    newName: eu.gcr.io/digdir-fdk-infra/fdk-dataset-event-publisher
    newTag: $(GIT_COMMIT_SHA)
  - name: fdk-data-service-event-publisher
    newName: eu.gcr.io/digdir-fdk-infra/fdk-data-service-event-publisher
    newTag: $(GIT_COMMIT_SHA)
  - name: fdk-concept-event-publisher
    newName: eu.gcr.io/digdir-fdk-infra/fdk-concept-event-publisher
    newTag: $(GIT_COMMIT_SHA)
  - name: fdk-information-model-event-publisher
    newName: eu.gcr.io/digdir-fdk-infra/fdk-information-model-event-publisher
    newTag: $(GIT_COMMIT_SHA)
