name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  test:
    name: Run tests when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-rust.yaml@chore/not/test
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build event-publishers when pull request is created
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    needs: [test]
    strategy:
      matrix:
        app_name: [fdk-dataset-event-publisher, fdk-data-service-event-publisher, fdk-concept-event-publisher, fdk-information-model-event-publisher, fdk-event-event-publisher, fdk-service-event-publisher]
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: ${{ matrix.app_name }}
      environment: staging
      build_env: true
      build_env_name: BINARY
      build_env_value: ${{ matrix.app_name }}
      monorepo_app: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy publishers to staging environment
    if: github.event.pull_request.draft == false
    needs: [test, build]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-kafka-event-publisher
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
