name: Deploy to production & demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests when merging to main
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-rust.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build event-publishers when merged to main
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    needs: [test]
    strategy:
      matrix:
        app_name: [fdk-dataset-event-publisher, fdk-data-service-event-publisher, fdk-concept-event-publisher]
    with:
      app_name: ${{ matrix.app_name }}
      environment: prod
      build_env: true
      build_env_name: BINARY
      build_env_value: ${{ matrix.app_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

  deploy:
    name: Deploy publishers to prod environment with reusable workflow
    needs: [test, build]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-kafka-event-publisher
      environment: prod
      cluster: digdir-fdk-prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_demo:
    name: Deploy publishers to demo environment with reusable workflow
    needs: [deploy]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-kafka-event-publisher
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
